WeaponTweakData = WeaponTweakData or class()
function WeaponTweakData:init()
	self:_create_table_structure()
	self:_init_data_player_weapons()
	self:_init_data_m4_npc()
	self:_init_data_m14_npc()
	self:_init_data_c45_npc()
	self:_init_data_beretta92_npc()
	self:_init_data_raging_bull_npc()
	self:_init_data_r870_npc()
	self:_init_data_mossberg_npc()
	self:_init_data_mp5_npc()
	self:_init_data_mac11_npc()
	self:_init_data_hk21_npc()
	self:_init_data_shield_pistol_npc()
	self:_init_data_sniper_rifle_npc()
	self:_init_data_m79_npc()
	self:_init_data_glock_18_npc()
	self:_init_data_ak47_npc()
	self:_init_data_sentry_gun_npc()
	self:_precalculate_values()
end
function WeaponTweakData:_init_data_c45_npc()
	self.c45_npc.sounds.prefix = "c45_npc"
	self.c45_npc.use_data.selection_index = 1
	self.c45_npc.DAMAGE = 1
	self.c45_npc.muzzleflash = "effects/particles/weapons/c45/muzzleflash_3dp"
	self.c45_npc.CLIP_AMMO_MAX = 10
	self.c45_npc.NR_CLIPS_MAX = 5
	self.c45_npc.hold = "pistol"
	self.c45_npc.hud_icon = self.c45.hud_icon
	self.c45_npc.alert_size = 2500
end
function WeaponTweakData:_init_data_beretta92_npc()
	self.beretta92_npc.sounds.prefix = "beretta_npc"
	self.beretta92_npc.use_data.selection_index = 1
	self.beretta92_npc.DAMAGE = 1
	self.beretta92_npc.muzzleflash = "effects/particles/weapons/silenced/muzzleflash_3dp"
	self.beretta92_npc.CLIP_AMMO_MAX = 14
	self.beretta92_npc.NR_CLIPS_MAX = 4
	self.beretta92_npc.hold = "pistol"
	self.beretta92_npc.hud_icon = self.beretta92.hud_icon
	self.beretta92_npc.alert_size = 300
end
function WeaponTweakData:_init_data_glock_18_npc()
	self.glock_18_npc.sounds.prefix = "stryk_npc"
	self.glock_18_npc.use_data.selection_index = 1
	self.glock_18_npc.DAMAGE = 1
	self.glock_18_npc.muzzleflash = "effects/particles/weapons/silenced/muzzleflash_3dp"
	self.glock_18_npc.CLIP_AMMO_MAX = 20
	self.glock_18_npc.NR_CLIPS_MAX = 8
	self.glock_18_npc.hold = "pistol"
	self.glock_18_npc.hud_icon = self.glock.hud_icon
	self.glock_18_npc.alert_size = 2500
end
function WeaponTweakData:_init_data_raging_bull_npc()
	self.raging_bull_npc.sounds.prefix = "ragingbull_npc"
	self.raging_bull_npc.use_data.selection_index = 1
	self.raging_bull_npc.DAMAGE = 1
	self.raging_bull_npc.muzzleflash = "effects/particles/weapons/raging/muzzleflash_3dp"
	self.raging_bull_npc.CLIP_AMMO_MAX = 6
	self.raging_bull_npc.NR_CLIPS_MAX = 8
	self.raging_bull_npc.hold = "pistol"
	self.raging_bull_npc.hud_icon = self.raging_bull.hud_icon
	self.raging_bull_npc.alert_size = 5000
end
function WeaponTweakData:_init_data_m4_npc()
	self.m4_npc.sounds.prefix = "m4_npc"
	self.m4_npc.use_data.selection_index = 2
	self.m4_npc.DAMAGE = 1.7
	self.m4_npc.muzzleflash = "effects/particles/weapons/rifle/muzzleflash_3dp"
	self.m4_npc.CLIP_AMMO_MAX = 20
	self.m4_npc.NR_CLIPS_MAX = 5
	self.m4_npc.auto.fire_rate = 0.2
	self.m4_npc.hold = "rifle"
	self.m4_npc.hud_icon = self.test_raycast_weapon.hud_icon
	self.m4_npc.alert_size = 5000
end
function WeaponTweakData:_init_data_ak47_npc()
	self.ak47_npc.sounds.prefix = "ak47_npc"
	self.ak47_npc.use_data.selection_index = 2
	self.ak47_npc.DAMAGE = 1.7
	self.ak47_npc.muzzleflash = "effects/particles/weapons/rifle/muzzleflash_3dp"
	self.ak47_npc.CLIP_AMMO_MAX = 20
	self.ak47_npc.NR_CLIPS_MAX = 5
	self.ak47_npc.auto.fire_rate = 0.2
	self.ak47_npc.hold = "rifle"
	self.ak47_npc.hud_icon = self.test_raycast_weapon.hud_icon
	self.ak47_npc.alert_size = 5000
end
function WeaponTweakData:_init_data_m14_npc()
	self.m14_npc.sounds.prefix = "m14_npc"
	self.m14_npc.use_data.selection_index = 2
	self.m14_npc.DAMAGE = 1.7
	self.m14_npc.muzzleflash = "effects/particles/weapons/m14/muzzleflash_3dp"
	self.m14_npc.CLIP_AMMO_MAX = 12
	self.m14_npc.NR_CLIPS_MAX = 8
	self.m14_npc.auto.fire_rate = 0.2
	self.m14_npc.hold = "rifle"
	self.m14_npc.hud_icon = self.m14.hud_icon
	self.m14_npc.alert_size = 5000
end
function WeaponTweakData:_init_data_r870_npc()
	self.r870_npc.sounds.prefix = "remington_npc"
	self.r870_npc.use_data.selection_index = 3
	self.r870_npc.DAMAGE = 6
	self.r870_npc.muzzleflash = "effects/particles/weapons/shotgun/muzzleflash_3dp"
	self.r870_npc.CLIP_AMMO_MAX = 6
	self.r870_npc.NR_CLIPS_MAX = 4
	self.r870_npc.hold = "rifle"
	self.r870_npc.hud_icon = self.r870_shotgun.hud_icon
	self.r870_npc.alert_size = 4500
end
function WeaponTweakData:_init_data_m79_npc()
	self.m79_npc.sounds.prefix = "gl_npc"
	self.m79_npc.use_data.selection_index = 3
	self.m79_npc.DAMAGE = 0
	self.m79_npc.muzzleflash = "effects/particles/weapons/m79/m79_fire_3dp"
	self.m79_npc.CLIP_AMMO_MAX = 1
	self.m79_npc.NR_CLIPS_MAX = 5
	self.m79_npc.hold = "rifle"
	self.m79_npc.hud_icon = self.m79.hud_icon
	self.m79_npc.alert_size = 1000
end
function WeaponTweakData:_init_data_mossberg_npc()
	self.mossberg_npc.sounds.prefix = "mossberg_npc"
	self.mossberg_npc.use_data.selection_index = 3
	self.mossberg_npc.DAMAGE = 6
	self.mossberg_npc.muzzleflash = "effects/particles/weapons/shotgun/muzzleflash_3dp"
	self.mossberg_npc.CLIP_AMMO_MAX = 4
	self.mossberg_npc.NR_CLIPS_MAX = 6
	self.mossberg_npc.hold = "rifle"
	self.mossberg_npc.hud_icon = self.mossberg.hud_icon
	self.mossberg_npc.alert_size = 3000
end
function WeaponTweakData:_init_data_mp5_npc()
	self.mp5_npc.sounds.prefix = "mp5_npc"
	self.mp5_npc.use_data.selection_index = 4
	self.mp5_npc.DAMAGE = 1
	self.mp5_npc.muzzleflash = "effects/particles/weapons/mp5/muzzleflash_3dp"
	self.mp5_npc.CLIP_AMMO_MAX = 30
	self.mp5_npc.NR_CLIPS_MAX = 5
	self.mp5_npc.auto.fire_rate = 0.1
	self.mp5_npc.hold = "rifle"
	self.mp5_npc.hud_icon = self.mp5.hud_icon
	self.mp5_npc.alert_size = 2500
end
function WeaponTweakData:_init_data_mac11_npc()
	self.mac11_npc.sounds.prefix = "mp5_npc"
	self.mac11_npc.use_data.selection_index = 4
	self.mac11_npc.DAMAGE = 1.75
	self.mac11_npc.muzzleflash = "effects/particles/weapons/silenced/muzzleflash_3dp"
	self.mac11_npc.CLIP_AMMO_MAX = 32
	self.mac11_npc.NR_CLIPS_MAX = 5
	self.mac11_npc.auto.fire_rate = 0.1
	self.mac11_npc.hold = "pistol"
	self.mac11_npc.hud_icon = self.mac11.hud_icon
	self.mac11_npc.alert_size = 1000
end
function WeaponTweakData:_init_data_hk21_npc()
	self.hk21_npc.sounds.prefix = "b21_npc"
	self.hk21_npc.use_data.selection_index = 2
	self.hk21_npc.DAMAGE = 1
	self.hk21_npc.muzzleflash = "effects/particles/weapons/hk21/muzzleflash_3dp"
	self.hk21_npc.CLIP_AMMO_MAX = 60
	self.hk21_npc.NR_CLIPS_MAX = 4
	self.hk21_npc.auto.fire_rate = 0.2
	self.hk21_npc.hold = "rifle"
	self.hk21_npc.hud_icon = self.hk21.hud_icon
	self.hk21_npc.alert_size = 5000
end
function WeaponTweakData:_init_data_shield_pistol_npc()
	self.shield_pistol_npc.sounds.prefix = "mp5_npc"
	self.shield_pistol_npc.use_data.selection_index = 1
	self.shield_pistol_npc.DAMAGE = 1
	self.shield_pistol_npc.muzzleflash = "effects/particles/weapons/mp5/muzzleflash_3dp"
	self.shield_pistol_npc.CLIP_AMMO_MAX = 32
	self.shield_pistol_npc.NR_CLIPS_MAX = 5
	self.shield_pistol_npc.auto = {}
	self.shield_pistol_npc.auto.fire_rate = 0.1
	self.shield_pistol_npc.hold = "shield"
	self.shield_pistol_npc.hud_icon = self.hk21.hud_icon
end
function WeaponTweakData:_init_data_sniper_rifle_npc()
	self.sniper_rifle_npc.sounds.prefix = "sniper_npc"
	self.sniper_rifle_npc.use_data.selection_index = 2
	self.sniper_rifle_npc.DAMAGE = 1.7
	self.sniper_rifle_npc.muzzleflash = "effects/particles/weapons/rifle/muzzleflash_3dp"
	self.sniper_rifle_npc.CLIP_AMMO_MAX = 20
	self.sniper_rifle_npc.NR_CLIPS_MAX = 5
	self.sniper_rifle_npc.auto.fire_rate = 0.2
	self.sniper_rifle_npc.hold = "rifle"
	self.sniper_rifle_npc.hud_icon = self.test_raycast_weapon.hud_icon
end
function WeaponTweakData:_init_data_sentry_gun_npc()
	self.sentry_gun.name_id = "debug_sentry_gun"
	self.sentry_gun.DAMAGE = 0.5
	self.sentry_gun.SPREAD = 3
	self.sentry_gun.FIRE_RANGE = 5000
	self.sentry_gun.muzzleflash = "effects/particles/weapons/m14/muzzleflash_3dp"
	self.sentry_gun.auto.fire_rate = 0.05
	self.sentry_gun.alert_size = 2500
	self.sentry_gun.SHIELD_DMG_MUL = 0
	self.sentry_gun.LOST_SIGHT_VERIFICATION = 0.1
	self.sentry_gun.DEATH_VERIFICATION = {0.6, 0.9}
	self.sentry_gun.DETECTION_RANGE = 1800
	self.sentry_gun.KEEP_FIRE_ANGLE = 0.8
	self.sentry_gun.MAX_VEL_SPIN = 150
	self.sentry_gun.MIN_VEL_SPIN = self.sentry_gun.MAX_VEL_SPIN * 0.05
	self.sentry_gun.SLOWDOWN_ANGLE_SPIN = 30
	self.sentry_gun.ACC_SPIN = self.sentry_gun.MAX_VEL_SPIN * 5
	self.sentry_gun.MAX_VEL_PITCH = 100
	self.sentry_gun.MIN_VEL_PITCH = self.sentry_gun.MAX_VEL_PITCH * 0.05
	self.sentry_gun.SLOWDOWN_ANGLE_PITCH = 20
	self.sentry_gun.ACC_PITCH = self.sentry_gun.MAX_VEL_PITCH * 5
	self.sentry_gun.challenges = {}
	self.sentry_gun.challenges.group = "sentry_gun"
	self.sentry_gun.challenges.weapon = "sentry_gun"
end
function WeaponTweakData:_init_data_player_weapons()
	local autohit_rifle_default, autohit_pistol_default, autohit_shotgun_default
	if SystemInfo:platform() == Idstring("WIN32") then
		autohit_rifle_default = {
			MIN_RATIO = 0.01,
			MAX_RATIO = 0.25,
			INIT_RATIO = 0.25,
			far_dis = 2500,
			far_angle = math.cos(0.2),
			near_angle = math.cos(4)
		}
		autohit_pistol_default = {
			MIN_RATIO = 0.01,
			MAX_RATIO = 0.25,
			INIT_RATIO = 0.25,
			far_dis = 5000,
			far_angle = math.cos(0.2),
			near_angle = math.cos(4)
		}
		autohit_shotgun_default = {
			MIN_RATIO = 0.15,
			MAX_RATIO = 0.3,
			INIT_RATIO = 0.3,
			far_dis = 5000,
			far_angle = math.cos(0.5),
			near_angle = math.cos(4)
		}
	else
		autohit_rifle_default = {
			MIN_RATIO = 0.25,
			MAX_RATIO = 0.6,
			INIT_RATIO = 0.6,
			far_dis = 5000,
			far_angle = math.cos(0.8),
			near_angle = math.cos(8)
		}
		autohit_pistol_default = {
			MIN_RATIO = 0.25,
			MAX_RATIO = 0.6,
			INIT_RATIO = 0.6,
			far_dis = 2500,
			far_angle = math.cos(0.8),
			near_angle = math.cos(8)
		}
		autohit_shotgun_default = {
			MIN_RATIO = 0.15,
			MAX_RATIO = 0.3,
			INIT_RATIO = 0.3,
			far_dis = 5000,
			far_angle = math.cos(0.6),
			near_angle = math.cos(5)
		}
	end
	self.crosshair = {}
	self.crosshair.MIN_OFFSET = 18
	self.crosshair.MAX_OFFSET = 150
	self.crosshair.MIN_KICK_OFFSET = 0
	self.crosshair.MAX_KICK_OFFSET = 100
	self.crosshair.DEFAULT_OFFSET = 0.16
	self.crosshair.DEFAULT_KICK_OFFSET = 0.6
	local damage_melee_default = 1.5
	local damage_melee_effect_multiplier_default = 1.75
	self.trip_mines = {}
	self.trip_mines.delay = 0.3
	self.trip_mines.damage = 100
	self.trip_mines.damage_size = 300
	self.trip_mines.alert_radius = 5000
	self.test_raycast_weapon = {}
	self.test_raycast_weapon.damage_melee = damage_melee_default
	self.test_raycast_weapon.damage_melee_effect_mul = damage_melee_effect_multiplier_default
	self.test_raycast_weapon.sounds = {}
	self.test_raycast_weapon.sounds.fire = "m4_fire"
	self.test_raycast_weapon.sounds.stop_fire = "m4_stop"
	self.test_raycast_weapon.sounds.dryfire = "m4_dryfire"
	self.test_raycast_weapon.sounds.enter_steelsight = "m4_tighten"
	self.test_raycast_weapon.sounds.enter_steelsight = "primary_steel_sight_enter"
	self.test_raycast_weapon.sounds.leave_steelsight = "primary_steel_sight_exit"
	self.test_raycast_weapon.timers = {}
	self.test_raycast_weapon.timers.reload_not_empty = 1.4
	self.test_raycast_weapon.timers.reload_empty = 1.9
	self.test_raycast_weapon.timers.unequip = 0.7
	self.test_raycast_weapon.timers.equip = 0.5
	self.test_raycast_weapon.name_id = "debug_test_raycast_weapon"
	self.test_raycast_weapon.hud_icon = "m4"
	self.test_raycast_weapon.description_id = "des_m4"
	self.test_raycast_weapon.muzzleflash = "effects/particles/weapons/rifle/muzzleflash"
	self.test_raycast_weapon.use_data = {}
	self.test_raycast_weapon.use_data.selection_index = 2
	self.test_raycast_weapon.DAMAGE = 2
	self.test_raycast_weapon.CLIP_AMMO_MAX = 20
	self.test_raycast_weapon.NR_CLIPS_MAX = 6
	self.test_raycast_weapon.AMMO_MAX = self.test_raycast_weapon.CLIP_AMMO_MAX * self.test_raycast_weapon.NR_CLIPS_MAX
	self.test_raycast_weapon.AMMO_PICKUP = {2, 10}
	self.test_raycast_weapon.auto = {}
	self.test_raycast_weapon.auto.fire_rate = 0.1
	self.test_raycast_weapon.spread = {}
	self.test_raycast_weapon.spread.standing = 4
	self.test_raycast_weapon.spread.crouching = 3
	self.test_raycast_weapon.spread.steelsight = 1
	self.test_raycast_weapon.spread.moving_standing = 6
	self.test_raycast_weapon.spread.moving_crouching = 5
	self.test_raycast_weapon.kick = {}
	self.test_raycast_weapon.kick.v = {}
	self.test_raycast_weapon.kick.v.standing = 0.3
	self.test_raycast_weapon.kick.v.crouching = 0.3
	self.test_raycast_weapon.kick.v.steelsight = -0.45
	self.test_raycast_weapon.kick.h = {}
	self.test_raycast_weapon.kick.h.standing = 0.7
	self.test_raycast_weapon.kick.h.crouching = 0.7
	self.test_raycast_weapon.kick.h.steelsight = -0.45
	self.test_raycast_weapon.crosshair = {}
	self.test_raycast_weapon.crosshair.standing = {}
	self.test_raycast_weapon.crosshair.crouching = {}
	self.test_raycast_weapon.crosshair.steelsight = {}
	self.test_raycast_weapon.crosshair.standing.offset = 0.16
	self.test_raycast_weapon.crosshair.standing.moving_offset = 0.8
	self.test_raycast_weapon.crosshair.standing.kick_offset = 0.6
	self.test_raycast_weapon.crosshair.crouching.offset = 0.08
	self.test_raycast_weapon.crosshair.crouching.moving_offset = 0.7
	self.test_raycast_weapon.crosshair.crouching.kick_offset = 0.4
	self.test_raycast_weapon.crosshair.steelsight.hidden = true
	self.test_raycast_weapon.crosshair.steelsight.offset = 0
	self.test_raycast_weapon.crosshair.steelsight.moving_offset = 0
	self.test_raycast_weapon.crosshair.steelsight.kick_offset = 0.1
	self.test_raycast_weapon.autohit = autohit_rifle_default
	self.test_raycast_weapon.animations = {}
	self.test_raycast_weapon.animations.fire = "recoil"
	self.test_raycast_weapon.animations.reload = "reload"
	self.test_raycast_weapon.animations.reload_not_empty = "reload_not_empty"
	self.test_raycast_weapon.animations.equip_id = "equip_m4"
	self.test_raycast_weapon.animations.recoil_steelsight = false
	self.test_raycast_weapon.fire_weapon_shaker_multiplier = 0.4
	self.test_raycast_weapon.challenges = {}
	self.test_raycast_weapon.challenges.group = "rifle"
	self.test_raycast_weapon.challenges.weapon = "m4"
	self.test_raycast_weapon.alert_size = 5000
	self.beretta92 = {}
	self.beretta92.damage_melee = damage_melee_default
	self.beretta92.damage_melee_effect_mul = damage_melee_effect_multiplier_default
	self.beretta92.sounds = {}
	self.beretta92.sounds.fire = "beretta_fire"
	self.beretta92.sounds.enter_steelsight = "pistol_steel_sight_enter"
	self.beretta92.sounds.leave_steelsight = "pistol_steel_sight_exit"
	self.beretta92.sounds.dryfire = "beretta_dryfire"
	self.beretta92.timers = {}
	self.beretta92.timers.reload_not_empty = 1.8
	self.beretta92.timers.reload_empty = 2.6
	self.beretta92.timers.unequip = 0.5
	self.beretta92.timers.equip = 0.5
	self.beretta92.name_id = "debug_beretta92"
	self.beretta92.hud_icon = "beretta92"
	self.beretta92.description_id = "des_beretta92"
	self.beretta92.hud_ammo = "guis/textures/ammo_9mm"
	self.beretta92.muzzleflash = "effects/particles/weapons/silenced/muzzleflash"
	self.beretta92.use_data = {}
	self.beretta92.use_data.selection_index = 1
	self.beretta92.DAMAGE = 1
	self.beretta92.CLIP_AMMO_MAX = 14
	self.beretta92.NR_CLIPS_MAX = 4
	self.beretta92.AMMO_MAX = self.beretta92.CLIP_AMMO_MAX * self.beretta92.NR_CLIPS_MAX
	self.beretta92.AMMO_PICKUP = {6, 8}
	self.beretta92.single = {}
	self.beretta92.single.fire_rate = 0.08
	self.beretta92.spread = {}
	self.beretta92.spread.standing = 3.5
	self.beretta92.spread.crouching = 3.5
	self.beretta92.spread.steelsight = 1.4
	self.beretta92.spread.moving_standing = 3.5
	self.beretta92.spread.moving_crouching = 3.5
	self.beretta92.kick = {}
	self.beretta92.kick.v = {}
	self.beretta92.kick.v.standing = 2
	self.beretta92.kick.v.crouching = 2
	self.beretta92.kick.v.steelsight = 1
	self.beretta92.crosshair = {}
	self.beretta92.crosshair.standing = {}
	self.beretta92.crosshair.crouching = {}
	self.beretta92.crosshair.steelsight = {}
	self.beretta92.crosshair.standing.offset = 0.2
	self.beretta92.crosshair.standing.moving_offset = 0.6
	self.beretta92.crosshair.standing.kick_offset = 0.4
	self.beretta92.crosshair.crouching.offset = 0.1
	self.beretta92.crosshair.crouching.moving_offset = 0.6
	self.beretta92.crosshair.crouching.kick_offset = 0.3
	self.beretta92.crosshair.steelsight.hidden = true
	self.beretta92.crosshair.steelsight.offset = 0
	self.beretta92.crosshair.steelsight.moving_offset = 0
	self.beretta92.crosshair.steelsight.kick_offset = 0.1
	self.beretta92.autohit = autohit_pistol_default
	self.beretta92.animations = {}
	self.beretta92.animations.fire = "recoil"
	self.beretta92.animations.reload = "reload"
	self.beretta92.animations.reload_not_empty = "reload_not_empty"
	self.beretta92.animations.equip_id = "equip_beretta"
	self.beretta92.animations.recoil_steelsight = true
	self.beretta92.challenges = {}
	self.beretta92.challenges.group = "handgun"
	self.beretta92.challenges.weapon = "beretta92"
	self.beretta92.alert_size = 300
	self.c45 = {}
	self.c45.damage_melee = damage_melee_default
	self.c45.damage_melee_effect_mul = damage_melee_effect_multiplier_default
	self.c45.sounds = {}
	self.c45.sounds.fire = "c45_fire"
	self.c45.sounds.dryfire = "c45_dryfire"
	self.c45.sounds.enter_steelsight = "pistol_steel_sight_enter"
	self.c45.sounds.leave_steelsight = "pistol_steel_sight_exit"
	self.c45.single = {}
	self.c45.single.fire_rate = 0.12
	self.c45.timers = {}
	self.c45.timers.reload_not_empty = 1.9
	self.c45.timers.reload_empty = 2.6
	self.c45.timers.unequip = 0.5
	self.c45.timers.equip = 0.5
	self.c45.name_id = "debug_c45"
	self.c45.hud_icon = "c45"
	self.c45.description_id = "des_c45"
	self.c45.hud_ammo = "guis/textures/ammo_9mm"
	self.c45.muzzleflash = "effects/particles/weapons/c45/muzzleflash"
	self.c45.use_data = {}
	self.c45.use_data.selection_index = 1
	self.c45.DAMAGE = 1.5
	self.c45.CLIP_AMMO_MAX = 10
	self.c45.NR_CLIPS_MAX = 5
	self.c45.AMMO_MAX = self.c45.CLIP_AMMO_MAX * self.c45.NR_CLIPS_MAX
	self.c45.AMMO_PICKUP = {4, 6}
	self.c45.spread = {}
	self.c45.spread.standing = 4.5
	self.c45.spread.crouching = 4.5
	self.c45.spread.steelsight = 1.7
	self.c45.spread.moving_standing = 4.5
	self.c45.spread.moving_crouching = 4.5
	self.c45.kick = {}
	self.c45.kick.v = {}
	self.c45.kick.v.standing = 2.5
	self.c45.kick.v.crouching = 2.5
	self.c45.kick.v.steelsight = 2.7
	self.c45.kick.h = {}
	self.c45.kick.h.standing = 2.5
	self.c45.kick.h.crouching = 2.5
	self.c45.kick.h.steelsight = 2.2
	self.c45.crosshair = {}
	self.c45.crosshair.standing = {}
	self.c45.crosshair.crouching = {}
	self.c45.crosshair.steelsight = {}
	self.c45.crosshair.standing.offset = 0.2
	self.c45.crosshair.standing.moving_offset = 0.6
	self.c45.crosshair.standing.kick_offset = 0.4
	self.c45.crosshair.crouching.offset = 0.1
	self.c45.crosshair.crouching.moving_offset = 0.6
	self.c45.crosshair.crouching.kick_offset = 0.3
	self.c45.crosshair.steelsight.hidden = true
	self.c45.crosshair.steelsight.offset = 0
	self.c45.crosshair.steelsight.moving_offset = 0
	self.c45.crosshair.steelsight.kick_offset = 0.1
	self.c45.autohit = autohit_pistol_default
	self.c45.animations = {}
	self.c45.animations.fire = "recoil"
	self.c45.animations.reload = "reload"
	self.c45.animations.reload_not_empty = "reload_not_empty"
	self.c45.animations.equip_id = "equip_c45"
	self.c45.animations.recoil_steelsight = true
	self.c45.challenges = {}
	self.c45.challenges.group = "handgun"
	self.c45.challenges.weapon = "c45"
	self.c45.alert_size = 2500
	self.raging_bull = {}
	self.raging_bull.damage_melee = damage_melee_default
	self.raging_bull.damage_melee_effect_mul = damage_melee_effect_multiplier_default
	self.raging_bull.sounds = {}
	self.raging_bull.sounds.fire = "ragingbull_fire"
	self.raging_bull.sounds.dryfire = "ragingbull_dryfire"
	self.raging_bull.sounds.enter_steelsight = "pistol_steel_sight_enter"
	self.raging_bull.sounds.leave_steelsight = "pistol_steel_sight_exit"
	self.raging_bull.timers = {}
	self.raging_bull.timers.reload_not_empty = 4.6
	self.raging_bull.timers.reload_empty = 4.6
	self.raging_bull.timers.unequip = 0.5
	self.raging_bull.timers.equip = 0.5
	self.raging_bull.single = {}
	self.raging_bull.single.fire_rate = 0.22
	self.raging_bull.name_id = "debug_raging_bull"
	self.raging_bull.hud_icon = "raging_bull"
	self.raging_bull.description_id = "des_raging_bull"
	self.raging_bull.hud_ammo = "guis/textures/ammo_9mm"
	self.raging_bull.muzzleflash = "effects/particles/weapons/raging/muzzleflash"
	self.raging_bull.use_data = {}
	self.raging_bull.use_data.selection_index = 1
	self.raging_bull.DAMAGE = 4.5
	self.raging_bull.CLIP_AMMO_MAX = 6
	self.raging_bull.NR_CLIPS_MAX = 6
	self.raging_bull.AMMO_MAX = self.raging_bull.CLIP_AMMO_MAX * self.raging_bull.NR_CLIPS_MAX
	self.raging_bull.AMMO_PICKUP = {1, 2}
	self.raging_bull.spread = {}
	self.raging_bull.spread.standing = 2.5
	self.raging_bull.spread.crouching = 2.5
	self.raging_bull.spread.steelsight = 1.8
	self.raging_bull.spread.moving_standing = 2.5
	self.raging_bull.spread.moving_crouching = 2.5
	self.raging_bull.kick = {}
	self.raging_bull.kick.v = {}
	self.raging_bull.kick.v.standing = 2.5
	self.raging_bull.kick.v.crouching = 2
	self.raging_bull.kick.v.steelsight = 5.6
	self.raging_bull.kick.h = {}
	self.raging_bull.kick.h.standing = 1.5
	self.raging_bull.kick.h.crouching = 1
	self.raging_bull.kick.h.steelsight = 1.6
	self.raging_bull.crosshair = {}
	self.raging_bull.crosshair.standing = {}
	self.raging_bull.crosshair.crouching = {}
	self.raging_bull.crosshair.steelsight = {}
	self.raging_bull.crosshair.standing.offset = 0.2
	self.raging_bull.crosshair.standing.moving_offset = 0.6
	self.raging_bull.crosshair.standing.kick_offset = 0.4
	self.raging_bull.crosshair.crouching.offset = 0.1
	self.raging_bull.crosshair.crouching.moving_offset = 0.6
	self.raging_bull.crosshair.crouching.kick_offset = 0.3
	self.raging_bull.crosshair.steelsight.hidden = true
	self.raging_bull.crosshair.steelsight.offset = 0
	self.raging_bull.crosshair.steelsight.moving_offset = 0
	self.raging_bull.crosshair.steelsight.kick_offset = 0.1
	self.raging_bull.autohit = autohit_pistol_default
	self.raging_bull.animations = {}
	self.raging_bull.animations.fire = "recoil"
	self.raging_bull.animations.reload = "reload"
	self.raging_bull.animations.reload_not_empty = "reload_not_empty"
	self.raging_bull.animations.equip_id = "equip_raging_bull"
	self.raging_bull.animations.recoil_steelsight = true
	self.raging_bull.fire_weapon_shaker_multiplier = 1
	self.raging_bull.challenges = {}
	self.raging_bull.challenges.group = "handgun"
	self.raging_bull.challenges.weapon = "bronco"
	self.raging_bull.alert_size = 5000
	self.glock = {}
	self.glock.damage_melee = damage_melee_default
	self.glock.damage_melee_effect_mul = damage_melee_effect_multiplier_default
	self.glock.sounds = {}
	self.glock.sounds.fire = "stryk_fire"
	self.glock.sounds.stop_fire = "stryk_stop"
	self.glock.sounds.dryfire = "stryk_dryfire"
	self.glock.sounds.enter_steelsight = "pistol_steel_sight_enter"
	self.glock.sounds.leave_steelsight = "pistol_steel_sight_exit"
	self.glock.timers = {}
	self.glock.timers.reload_not_empty = 2.5
	self.glock.timers.reload_empty = 2.7
	self.glock.timers.unequip = 0.5
	self.glock.timers.equip = 0.5
	self.glock.name_id = "debug_glock"
	self.glock.hud_icon = "glock"
	self.glock.description_id = "des_glock"
	self.glock.hud_ammo = "guis/textures/ammo_small_9mm"
	self.glock.muzzleflash = "effects/particles/weapons/silenced/muzzleflash"
	self.glock.use_data = {}
	self.glock.use_data.selection_index = 1
	self.glock.DAMAGE = 1
	self.glock.CLIP_AMMO_MAX = 20
	self.glock.NR_CLIPS_MAX = 8
	self.glock.AMMO_MAX = self.beretta92.CLIP_AMMO_MAX * self.beretta92.NR_CLIPS_MAX
	self.glock.AMMO_PICKUP = {5, 7}
	self.glock.auto = {}
	self.glock.auto.fire_rate = 0.066
	self.glock.spread = {}
	self.glock.spread.standing = 4
	self.glock.spread.crouching = 4
	self.glock.spread.steelsight = 1.6
	self.glock.spread.moving_standing = 4
	self.glock.spread.moving_crouching = 4
	self.glock.kick = {}
	self.glock.kick.v = {}
	self.glock.kick.v.standing = -0.8
	self.glock.kick.v.crouching = -0.8
	self.glock.kick.v.steelsight = -0.8
	self.glock.kick.h = {}
	self.glock.kick.h.standing = 0.8
	self.glock.kick.h.crouching = 0.8
	self.glock.kick.h.steelsight = 0.8
	self.glock.crosshair = {}
	self.glock.crosshair.standing = {}
	self.glock.crosshair.crouching = {}
	self.glock.crosshair.steelsight = {}
	self.glock.crosshair.standing.offset = 0.3
	self.glock.crosshair.standing.moving_offset = 0.5
	self.glock.crosshair.standing.kick_offset = 0.6
	self.glock.crosshair.crouching.offset = 0.2
	self.glock.crosshair.crouching.moving_offset = 0.5
	self.glock.crosshair.crouching.kick_offset = 0.3
	self.glock.crosshair.steelsight.hidden = true
	self.glock.crosshair.steelsight.offset = 0.2
	self.glock.crosshair.steelsight.moving_offset = 0.2
	self.glock.crosshair.steelsight.kick_offset = 0.3
	self.glock.autohit = autohit_pistol_default
	self.glock.animations = {}
	self.glock.animations.fire = "recoil"
	self.glock.animations.reload = "reload"
	self.glock.animations.reload_not_empty = "reload_not_empty"
	self.glock.animations.equip_id = "equip_beretta"
	self.glock.animations.recoil_steelsight = true
	self.glock.challenges = {}
	self.glock.challenges.group = "handgun"
	self.glock.challenges.weapon = "glock"
	self.glock.alert_size = 5000
	self.r870_shotgun = {}
	self.r870_shotgun.damage_melee = damage_melee_default
	self.r870_shotgun.damage_melee_effect_mul = damage_melee_effect_multiplier_default
	self.r870_shotgun.sounds = {}
	self.r870_shotgun.sounds.fire = "remington_fire"
	self.r870_shotgun.sounds.dryfire = "remington_dryfire"
	self.r870_shotgun.sounds.enter_steelsight = "primary_steel_sight_enter"
	self.r870_shotgun.sounds.leave_steelsight = "primary_steel_sight_exit"
	self.r870_shotgun.timers = {}
	self.r870_shotgun.timers.unequip = 0.5
	self.r870_shotgun.timers.equip = 0.5
	self.r870_shotgun.name_id = "debug_r870_shotgun"
	self.r870_shotgun.hud_icon = "r870_shotgun"
	self.r870_shotgun.description_id = "des_r870_shotgun"
	self.r870_shotgun.hud_ammo = "guis/textures/ammo_shell"
	self.r870_shotgun.muzzleflash = "effects/particles/weapons/shotgun/muzzleflash"
	self.r870_shotgun.use_data = {}
	self.r870_shotgun.use_data.selection_index = 2
	self.r870_shotgun.DAMAGE = 6
	self.r870_shotgun.damage_near = 500
	self.r870_shotgun.damage_far = 4000
	self.r870_shotgun.CLIP_AMMO_MAX = 6
	self.r870_shotgun.NR_CLIPS_MAX = 5
	self.r870_shotgun.AMMO_MAX = self.r870_shotgun.CLIP_AMMO_MAX * self.r870_shotgun.NR_CLIPS_MAX
	self.r870_shotgun.AMMO_PICKUP = {1, 2}
	self.r870_shotgun.single = {}
	self.r870_shotgun.single.fire_rate = 0.8
	self.r870_shotgun.spread = {}
	self.r870_shotgun.spread.standing = 4
	self.r870_shotgun.spread.crouching = 4
	self.r870_shotgun.spread.steelsight = 3
	self.r870_shotgun.spread.moving_standing = 4
	self.r870_shotgun.spread.moving_crouching = 4
	self.r870_shotgun.kick = {}
	self.r870_shotgun.kick.v = {}
	self.r870_shotgun.kick.v.standing = 2
	self.r870_shotgun.kick.v.crouching = 2
	self.r870_shotgun.kick.v.steelsight = 0.6
	self.r870_shotgun.kick.h = {}
	self.r870_shotgun.kick.h.standing = 0.2
	self.r870_shotgun.kick.h.crouching = 0.2
	self.r870_shotgun.kick.h.steelsight = 0.2
	self.r870_shotgun.crosshair = {}
	self.r870_shotgun.crosshair.standing = {}
	self.r870_shotgun.crosshair.crouching = {}
	self.r870_shotgun.crosshair.steelsight = {}
	self.r870_shotgun.crosshair.standing.offset = 0.7
	self.r870_shotgun.crosshair.standing.moving_offset = 0.7
	self.r870_shotgun.crosshair.standing.kick_offset = 0.8
	self.r870_shotgun.crosshair.crouching.offset = 0.65
	self.r870_shotgun.crosshair.crouching.moving_offset = 0.65
	self.r870_shotgun.crosshair.crouching.kick_offset = 0.75
	self.r870_shotgun.crosshair.steelsight.hidden = true
	self.r870_shotgun.crosshair.steelsight.offset = 0
	self.r870_shotgun.crosshair.steelsight.moving_offset = 0
	self.r870_shotgun.crosshair.steelsight.kick_offset = 0
	self.r870_shotgun.autohit = autohit_shotgun_default
	self.r870_shotgun.animations = {}
	self.r870_shotgun.animations.fire = "recoil"
	self.r870_shotgun.animations.fire_steelsight = "recoil_zoom"
	self.r870_shotgun.animations.reload_exit = "reload"
	self.r870_shotgun.animations.equip_id = "equip_r870_shotgun"
	self.r870_shotgun.animations.recoil_steelsight = true
	self.r870_shotgun.fire_weapon_shaker_multiplier = 2
	self.r870_shotgun.challenges = {}
	self.r870_shotgun.challenges.group = "shotgun"
	self.r870_shotgun.challenges.weapon = "reinbeck"
	self.r870_shotgun.alert_size = 4500
	self.mossberg = {}
	self.mossberg.damage_melee = damage_melee_default
	self.mossberg.damage_melee_effect_mul = damage_melee_effect_multiplier_default
	self.mossberg.sounds = {}
	self.mossberg.sounds.fire = "mossberg_fire"
	self.mossberg.sounds.dryfire = "mossberg_dryfire"
	self.mossberg.sounds.enter_steelsight = "secondary_steel_sight_enter"
	self.mossberg.sounds.leave_steelsight = "secondary_steel_sight_exit"
	self.mossberg.timers = {}
	self.mossberg.timers.unequip = 0.5
	self.mossberg.timers.equip = 0.5
	self.mossberg.name_id = "debug_mossberg"
	self.mossberg.hud_icon = "mossberg"
	self.mossberg.description_id = "des_mossberg"
	self.mossberg.hud_ammo = "guis/textures/ammo_shell"
	self.mossberg.muzzleflash = "effects/particles/weapons/shotgun/muzzleflash"
	self.mossberg.use_data = {}
	self.mossberg.use_data.selection_index = 3
	self.mossberg.DAMAGE = 4
	self.mossberg.damage_near = 500
	self.mossberg.damage_far = 2000
	self.mossberg.CLIP_AMMO_MAX = 4
	self.mossberg.NR_CLIPS_MAX = 6
	self.mossberg.AMMO_MAX = self.mossberg.CLIP_AMMO_MAX * self.mossberg.NR_CLIPS_MAX
	self.mossberg.AMMO_PICKUP = {0, 1}
	self.mossberg.single = {}
	self.mossberg.single.fire_rate = 0.8
	self.mossberg.spread = {}
	self.mossberg.spread.standing = 5
	self.mossberg.spread.crouching = 5
	self.mossberg.spread.steelsight = 4
	self.mossberg.spread.moving_standing = 5
	self.mossberg.spread.moving_crouching = 5
	self.mossberg.kick = {}
	self.mossberg.kick.v = {}
	self.mossberg.kick.v.standing = 2
	self.mossberg.kick.v.crouching = 2
	self.mossberg.kick.v.steelsight = 0.7
	self.mossberg.kick.h = {}
	self.mossberg.kick.h.standing = 0.3
	self.mossberg.kick.h.crouching = 0.3
	self.mossberg.kick.h.steelsight = 0.2
	self.mossberg.crosshair = {}
	self.mossberg.crosshair.standing = {}
	self.mossberg.crosshair.crouching = {}
	self.mossberg.crosshair.steelsight = {}
	self.mossberg.crosshair.standing.offset = 0.4
	self.mossberg.crosshair.standing.moving_offset = 0.7
	self.mossberg.crosshair.standing.kick_offset = 0.6
	self.mossberg.crosshair.crouching.offset = 0.3
	self.mossberg.crosshair.crouching.moving_offset = 0.6
	self.mossberg.crosshair.crouching.kick_offset = 0.4
	self.mossberg.crosshair.steelsight.hidden = true
	self.mossberg.crosshair.steelsight.offset = 0.3
	self.mossberg.crosshair.steelsight.moving_offset = 0.6
	self.mossberg.crosshair.steelsight.kick_offset = 0.4
	self.mossberg.autohit = autohit_shotgun_default
	self.mossberg.animations = {}
	self.mossberg.animations.fire = "recoil"
	self.mossberg.animations.fire_steelsight = "recoil_zoom"
	self.mossberg.animations.reload_exit = "reload"
	self.mossberg.animations.equip_id = "equip_mossberg_shotgun"
	self.mossberg.animations.recoil_steelsight = true
	self.mossberg.fire_weapon_shaker_multiplier = 2
	self.mossberg.challenges = {}
	self.mossberg.challenges.group = "shotgun"
	self.mossberg.challenges.weapon = "mossberg"
	self.mossberg.alert_size = 3000
	self.m4 = self.test_raycast_weapon
	self.mp5 = {}
	self.mp5.damage_melee = damage_melee_default
	self.mp5.damage_melee_effect_mul = damage_melee_effect_multiplier_default
	self.mp5.sounds = {}
	self.mp5.sounds.fire = "mp5_fire"
	self.mp5.sounds.stop_fire = "mp5_stop"
	self.mp5.sounds.dryfire = "mp5_dryfire"
	self.mp5.sounds.enter_steelsight = "secondary_steel_sight_enter"
	self.mp5.sounds.leave_steelsight = "secondary_steel_sight_exit"
	self.mp5.timers = {}
	self.mp5.timers.reload_not_empty = 2.2
	self.mp5.timers.reload_empty = 2.8
	self.mp5.timers.unequip = 0.7
	self.mp5.timers.equip = 0.5
	self.mp5.name_id = "debug_mp5"
	self.mp5.hud_icon = "mp5"
	self.mp5.description_id = "des_mp5"
	self.mp5.hud_ammo = "guis/textures/ammo_9mm"
	self.mp5.muzzleflash = "effects/particles/weapons/mp5/muzzleflash"
	self.mp5.use_data = {}
	self.mp5.use_data.selection_index = 3
	self.mp5.DAMAGE = 1.15
	self.mp5.CLIP_AMMO_MAX = 30
	self.mp5.NR_CLIPS_MAX = 5
	self.mp5.AMMO_MAX = self.mp5.CLIP_AMMO_MAX * self.mp5.NR_CLIPS_MAX
	self.mp5.AMMO_PICKUP = {2, 7}
	self.mp5.auto = {}
	self.mp5.auto.fire_rate = 0.1
	self.mp5.spread = {}
	self.mp5.spread.standing = 3.5
	self.mp5.spread.crouching = 2.5
	self.mp5.spread.steelsight = 1.7
	self.mp5.spread.moving_standing = 4.5
	self.mp5.spread.moving_crouching = 3.8
	self.mp5.kick = {}
	self.mp5.kick.v = {}
	self.mp5.kick.v.standing = 0.45
	self.mp5.kick.v.crouching = 0.4
	self.mp5.kick.v.steelsight = -0.45
	self.mp5.kick.h = {}
	self.mp5.kick.h.standing = 0.45
	self.mp5.kick.h.crouching = 0.4
	self.mp5.kick.h.steelsight = 0.45
	self.mp5.crosshair = {}
	self.mp5.crosshair.standing = {}
	self.mp5.crosshair.crouching = {}
	self.mp5.crosshair.steelsight = {}
	self.mp5.crosshair.standing.offset = 0.5
	self.mp5.crosshair.standing.moving_offset = 0.6
	self.mp5.crosshair.standing.kick_offset = 0.7
	self.mp5.crosshair.crouching.offset = 0.4
	self.mp5.crosshair.crouching.moving_offset = 0.5
	self.mp5.crosshair.crouching.kick_offset = 0.6
	self.mp5.crosshair.steelsight.hidden = true
	self.mp5.crosshair.steelsight.offset = 0
	self.mp5.crosshair.steelsight.moving_offset = 0
	self.mp5.crosshair.steelsight.kick_offset = 0
	self.mp5.autohit = autohit_pistol_default
	self.mp5.animations = {}
	self.mp5.animations.fire = "recoil"
	self.mp5.animations.reload = "reload"
	self.mp5.animations.reload_not_empty = "reload_not_empty"
	self.mp5.animations.equip_id = "equip_mp5_rifle"
	self.mp5.animations.recoil_steelsight = false
	self.mp5.fire_weapon_shaker_multiplier = 0.5
	self.mp5.challenges = {}
	self.mp5.challenges.group = "sub_machingun"
	self.mp5.challenges.weapon = "mp5"
	self.mp5.alert_size = 2500
	self.mac11 = {}
	self.mac11.damage_melee = damage_melee_default
	self.mac11.damage_melee_effect_mul = damage_melee_effect_multiplier_default
	self.mac11.sounds = {}
	self.mac11.sounds.fire = "mk11_fire"
	self.mac11.sounds.stop_fire = "mk11_stop"
	self.mac11.sounds.dryfire = "mk11_dryfire"
	self.mac11.sounds.enter_steelsight = "secondary_steel_sight_enter"
	self.mac11.sounds.leave_steelsight = "secondary_steel_sight_exit"
	self.mac11.timers = {}
	self.mac11.timers.reload_not_empty = 2.15
	self.mac11.timers.reload_empty = 3.1
	self.mac11.timers.unequip = 0.7
	self.mac11.timers.equip = 0.5
	self.mac11.name_id = "debug_mac11"
	self.mac11.hud_icon = "mac11"
	self.mac11.description_id = "des_mac11"
	self.mac11.hud_ammo = "guis/textures/ammo_small_9mm"
	self.mac11.muzzleflash = "effects/particles/weapons/silenced/muzzleflash"
	self.mac11.use_data = {}
	self.mac11.use_data.selection_index = 3
	self.mac11.DAMAGE = 1.3
	self.mac11.CLIP_AMMO_MAX = 30
	self.mac11.NR_CLIPS_MAX = 5
	self.mac11.AMMO_MAX = self.mac11.CLIP_AMMO_MAX * self.mac11.NR_CLIPS_MAX
	self.mac11.AMMO_PICKUP = {2, 7}
	self.mac11.auto = {}
	self.mac11.auto.fire_rate = 0.066
	self.mac11.spread = {}
	self.mac11.spread.standing = 4
	self.mac11.spread.crouching = 3
	self.mac11.spread.steelsight = 2.2
	self.mac11.spread.moving_standing = 5
	self.mac11.spread.moving_crouching = 4
	self.mac11.kick = {}
	self.mac11.kick.v = {}
	self.mac11.kick.v.standing = 0.5
	self.mac11.kick.v.crouching = 0.4
	self.mac11.kick.v.steelsight = -0.75
	self.mac11.kick.h = {}
	self.mac11.kick.h.standing = 0.5
	self.mac11.kick.h.crouching = 0.4
	self.mac11.kick.h.steelsight = -0.75
	self.mac11.crosshair = {}
	self.mac11.crosshair.standing = {}
	self.mac11.crosshair.crouching = {}
	self.mac11.crosshair.steelsight = {}
	self.mac11.crosshair.standing.offset = 0.4
	self.mac11.crosshair.standing.moving_offset = 0.7
	self.mac11.crosshair.standing.kick_offset = 0.6
	self.mac11.crosshair.crouching.offset = 0.3
	self.mac11.crosshair.crouching.moving_offset = 0.6
	self.mac11.crosshair.crouching.kick_offset = 0.4
	self.mac11.crosshair.steelsight.hidden = true
	self.mac11.crosshair.steelsight.offset = 0
	self.mac11.crosshair.steelsight.moving_offset = 0
	self.mac11.crosshair.steelsight.kick_offset = 0.4
	self.mac11.autohit = autohit_pistol_default
	self.mac11.animations = {}
	self.mac11.animations.fire = "recoil"
	self.mac11.animations.reload = "reload"
	self.mac11.animations.reload_not_empty = "reload_not_empty"
	self.mac11.animations.equip_id = "equip_mac11_rifle"
	self.mac11.animations.recoil_steelsight = false
	self.mac11.fire_weapon_shaker_multiplier = 1
	self.mac11.challenges = {}
	self.mac11.challenges.group = "sub_machingun"
	self.mac11.challenges.weapon = "mac11"
	self.mac11.alert_size = 300
	self.m14 = {}
	self.m14.damage_melee = damage_melee_default
	self.m14.damage_melee_effect_mul = damage_melee_effect_multiplier_default
	self.m14.sounds = {}
	self.m14.sounds.fire = "m14_fire"
	self.m14.sounds.dryfire = "m14_dryfire"
	self.m14.sounds.enter_steelsight = "primary_steel_sight_enter"
	self.m14.sounds.leave_steelsight = "primary_steel_sight_exit"
	self.m14.timers = {}
	self.m14.timers.reload_not_empty = 1.71
	self.m14.timers.reload_empty = 2.61
	self.m14.timers.unequip = 0.7
	self.m14.timers.equip = 0.5
	self.m14.name_id = "debug_m14"
	self.m14.hud_icon = "m14"
	self.m14.description_id = "des_m14"
	self.m14.muzzleflash = "effects/particles/weapons/m14/muzzleflash"
	self.m14.use_data = {}
	self.m14.use_data.selection_index = 2
	self.m14.DAMAGE = 4
	self.m14.CLIP_AMMO_MAX = 12
	self.m14.NR_CLIPS_MAX = 6
	self.m14.AMMO_MAX = self.m14.CLIP_AMMO_MAX * self.m14.NR_CLIPS_MAX
	self.m14.AMMO_PICKUP = {1, 5}
	self.m14.single = {}
	self.m14.single.fire_rate = 0.1
	self.m14.spread = {}
	self.m14.spread.standing = 7
	self.m14.spread.crouching = 6
	self.m14.spread.steelsight = 0.1
	self.m14.spread.moving_standing = 10
	self.m14.spread.moving_crouching = 8
	self.m14.kick = {}
	self.m14.kick.v = {}
	self.m14.kick.v.standing = 3.5
	self.m14.kick.v.crouching = 3.2
	self.m14.kick.v.steelsight = 3
	self.m14.kick.h = {}
	self.m14.kick.h.standing = 0.45
	self.m14.kick.h.crouching = 0.35
	self.m14.kick.h.steelsight = 2
	self.m14.crosshair = {}
	self.m14.crosshair.standing = {}
	self.m14.crosshair.crouching = {}
	self.m14.crosshair.steelsight = {}
	self.m14.crosshair.standing.offset = 0.16
	self.m14.crosshair.standing.moving_offset = 0.8
	self.m14.crosshair.standing.kick_offset = 0.6
	self.m14.crosshair.crouching.offset = 0.08
	self.m14.crosshair.crouching.moving_offset = 0.7
	self.m14.crosshair.crouching.kick_offset = 0.4
	self.m14.crosshair.steelsight.hidden = true
	self.m14.crosshair.steelsight.offset = 0
	self.m14.crosshair.steelsight.moving_offset = 0
	self.m14.crosshair.steelsight.kick_offset = 0.1
	self.m14.autohit = autohit_rifle_default
	self.m14.animations = {}
	self.m14.animations.fire = "recoil"
	self.m14.animations.reload = "reload"
	self.m14.animations.reload_not_empty = "reload_not_empty"
	self.m14.animations.equip_id = "equip_m14_rifle"
	self.m14.animations.recoil_steelsight = false
	self.m14.challenges = {}
	self.m14.challenges.group = "rifle"
	self.m14.challenges.weapon = "m14"
	self.m14.alert_size = 5000
	self.hk21 = {}
	self.hk21.damage_melee = damage_melee_default
	self.hk21.damage_melee_effect_mul = damage_melee_effect_multiplier_default
	self.hk21.sounds = {}
	self.hk21.sounds.fire = "b21_fire"
	self.hk21.sounds.stop_fire = "b21_stop"
	self.hk21.sounds.dryfire = "b21_dryfire"
	self.hk21.sounds.enter_steelsight = "m4_tighten"
	self.hk21.sounds.enter_steelsight = "primary_steel_sight_enter"
	self.hk21.sounds.leave_steelsight = "primary_steel_sight_exit"
	self.hk21.timers = {}
	self.hk21.timers.reload_not_empty = 4.25
	self.hk21.timers.reload_empty = 5.4
	self.hk21.timers.unequip = 1
	self.hk21.timers.equip = 0.5
	self.hk21.name_id = "debug_hk21"
	self.hk21.hud_icon = "hk21"
	self.hk21.description_id = "des_hk21"
	self.hk21.hud_ammo = "guis/textures/ammo_small"
	self.hk21.muzzleflash = "effects/particles/weapons/hk21/muzzleflash"
	self.hk21.use_data = {}
	self.hk21.use_data.selection_index = 2
	self.hk21.DAMAGE = 2.5
	self.hk21.CLIP_AMMO_MAX = 80
	self.hk21.NR_CLIPS_MAX = 3
	self.hk21.AMMO_MAX = self.hk21.CLIP_AMMO_MAX * self.hk21.NR_CLIPS_MAX
	self.hk21.AMMO_PICKUP = {2, 10}
	self.hk21.auto = {}
	self.hk21.auto.fire_rate = 0.1333
	self.hk21.spread = {}
	self.hk21.spread.standing = 2.5
	self.hk21.spread.crouching = 2.5
	self.hk21.spread.steelsight = 2.5
	self.hk21.spread.moving_standing = 4
	self.hk21.spread.moving_crouching = 3.5
	self.hk21.kick = {}
	self.hk21.kick.v = {}
	self.hk21.kick.v.standing = -1
	self.hk21.kick.v.crouching = -0.9
	self.hk21.kick.v.steelsight = -0.65
	self.hk21.kick.h = {}
	self.hk21.kick.h.standing = -0.8
	self.hk21.kick.h.crouching = -0.7
	self.hk21.kick.h.steelsight = -0.65
	self.hk21.crosshair = {}
	self.hk21.crosshair.standing = {}
	self.hk21.crosshair.crouching = {}
	self.hk21.crosshair.steelsight = {}
	self.hk21.crosshair.standing.offset = 0.16
	self.hk21.crosshair.standing.moving_offset = 0.8
	self.hk21.crosshair.standing.kick_offset = 0.6
	self.hk21.crosshair.crouching.offset = 0.08
	self.hk21.crosshair.crouching.moving_offset = 0.7
	self.hk21.crosshair.crouching.kick_offset = 0.4
	self.hk21.crosshair.steelsight.hidden = true
	self.hk21.crosshair.steelsight.offset = 0
	self.hk21.crosshair.steelsight.moving_offset = 0
	self.hk21.crosshair.steelsight.kick_offset = 0.1
	self.hk21.autohit = autohit_rifle_default
	self.hk21.animations = {}
	self.hk21.animations.fire = "recoil"
	self.hk21.animations.reload = "reload"
	self.hk21.animations.reload_not_empty = "reload_not_empty"
	self.hk21.animations.unequip = "unequip_hk21_rifle"
	self.hk21.animations.equip_id = "equip_hk21_rifle"
	self.hk21.animations.recoil_steelsight = false
	self.hk21.challenges = {}
	self.hk21.challenges.group = "rifle"
	self.hk21.challenges.weapon = "hk21"
	self.hk21.alert_size = 5000
	self.m79 = {}
	self.m79.damage_melee = damage_melee_default
	self.m79.damage_melee_effect_mul = damage_melee_effect_multiplier_default
	self.m79.sounds = {}
	self.m79.sounds.fire = "gl_fire"
	self.m79.sounds.dryfire = "gl_dryfire"
	self.m79.sounds.enter_steelsight = "secondary_steel_sight_enter"
	self.m79.sounds.leave_steelsight = "secondary_steel_sight_exit"
	self.m79.timers = {}
	self.m79.timers.reload_not_empty = 4.3
	self.m79.timers.reload_empty = 4.3
	self.m79.timers.unequip = 0.7
	self.m79.timers.equip = 0.5
	self.m79.name_id = "debug_m79"
	self.m79.hud_icon = "m79"
	self.m79.description_id = "des_m79"
	self.m79.hud_ammo = "guis/textures/ammo_grenade"
	self.m79.muzzleflash = "effects/particles/weapons/m14/muzzleflash"
	self.m79.use_data = {}
	self.m79.use_data.selection_index = 3
	self.m79.DAMAGE = 40
	self.m79.EXPLOSION_RANGE = 500
	self.m79.DAMAGE_CURVE_POW = 5
	self.m79.CLIP_AMMO_MAX = 1
	self.m79.NR_CLIPS_MAX = 4
	self.m79.AMMO_MAX = self.m79.CLIP_AMMO_MAX * self.m79.NR_CLIPS_MAX
	self.m79.AMMO_PICKUP = {-4, 1}
	self.m79.single = {}
	self.m79.single.fire_rate = 0.1
	self.m79.spread = {}
	self.m79.spread.standing = 7
	self.m79.spread.crouching = 6
	self.m79.spread.steelsight = 0.1
	self.m79.spread.moving_standing = 10
	self.m79.spread.moving_crouching = 8
	self.m79.kick = {}
	self.m79.kick.v = {}
	self.m79.kick.v.standing = 3.5
	self.m79.kick.v.crouching = 3.2
	self.m79.kick.v.steelsight = 3.2
	self.m79.kick.h = {}
	self.m79.kick.h.standing = 0.45
	self.m79.kick.h.crouching = 0.35
	self.m79.kick.h.steelsight = 1
	self.m79.crosshair = {}
	self.m79.crosshair.standing = {}
	self.m79.crosshair.crouching = {}
	self.m79.crosshair.steelsight = {}
	self.m79.crosshair.standing.offset = 0.16
	self.m79.crosshair.standing.moving_offset = 0.8
	self.m79.crosshair.standing.kick_offset = 0.6
	self.m79.crosshair.standing.hidden = true
	self.m79.crosshair.crouching.offset = 0.08
	self.m79.crosshair.crouching.moving_offset = 0.7
	self.m79.crosshair.crouching.kick_offset = 0.4
	self.m79.crosshair.crouching.hidden = true
	self.m79.crosshair.steelsight.hidden = true
	self.m79.crosshair.steelsight.offset = 0
	self.m79.crosshair.steelsight.moving_offset = 0
	self.m79.crosshair.steelsight.kick_offset = 0.1
	self.m79.autohit = autohit_rifle_default
	self.m79.animations = {}
	self.m79.animations.fire = "recoil"
	self.m79.animations.reload = "reload"
	self.m79.animations.reload_not_empty = "reload"
	self.m79.animations.equip_id = "equip_m14_rifle"
	self.m79.animations.recoil_steelsight = false
	self.m79.challenges = {}
	self.m79.challenges.group = "grenade_launcher"
	self.m79.challenges.weapon = "m79"
	self.m79.alert_size = 5000
	self.ak47 = {}
	self.ak47.damage_melee = damage_melee_default
	self.ak47.damage_melee_effect_mul = damage_melee_effect_multiplier_default
	self.ak47.sounds = {}
	self.ak47.sounds.fire = "ak47_fire"
	self.ak47.sounds.stop_fire = "ak47_stop"
	self.ak47.sounds.dryfire = "ak47_dryfire"
	self.ak47.sounds.enter_steelsight = "primary_steel_sight_enter"
	self.ak47.sounds.leave_steelsight = "primary_steel_sight_exit"
	self.ak47.timers = {}
	self.ak47.timers.reload_not_empty = 2.3
	self.ak47.timers.reload_empty = 3.9
	self.ak47.timers.unequip = 0.7
	self.ak47.timers.equip = 0.5
	self.ak47.name_id = "debug_ak47"
	self.ak47.hud_icon = "ak"
	self.ak47.description_id = "des_ak47"
	self.ak47.muzzleflash = "effects/particles/weapons/rifle/muzzleflash"
	self.ak47.use_data = {}
	self.ak47.use_data.selection_index = 2
	self.ak47.DAMAGE = 2.7
	self.ak47.CLIP_AMMO_MAX = 25
	self.ak47.NR_CLIPS_MAX = 5
	self.ak47.AMMO_MAX = self.ak47.CLIP_AMMO_MAX * self.ak47.NR_CLIPS_MAX
	self.ak47.AMMO_PICKUP = {2, 8}
	self.ak47.auto = {}
	self.ak47.auto.fire_rate = 0.07
	self.ak47.spread = {}
	self.ak47.spread.standing = 5
	self.ak47.spread.crouching = 4
	self.ak47.spread.steelsight = 1.5
	self.ak47.spread.moving_standing = 6
	self.ak47.spread.moving_crouching = 5.5
	self.ak47.kick = {}
	self.ak47.kick.v = {}
	self.ak47.kick.v.standing = 0.7
	self.ak47.kick.v.crouching = 0.7
	self.ak47.kick.v.steelsight = -0.8
	self.ak47.kick.h = {}
	self.ak47.kick.h.standing = 0.8
	self.ak47.kick.h.crouching = 0.8
	self.ak47.kick.h.steelsight = -0.9
	self.ak47.crosshair = {}
	self.ak47.crosshair.standing = {}
	self.ak47.crosshair.crouching = {}
	self.ak47.crosshair.steelsight = {}
	self.ak47.crosshair.standing.offset = 0.16
	self.ak47.crosshair.standing.moving_offset = 0.8
	self.ak47.crosshair.standing.kick_offset = 0.6
	self.ak47.crosshair.crouching.offset = 0.08
	self.ak47.crosshair.crouching.moving_offset = 0.7
	self.ak47.crosshair.crouching.kick_offset = 0.4
	self.ak47.crosshair.steelsight.hidden = true
	self.ak47.crosshair.steelsight.offset = 0
	self.ak47.crosshair.steelsight.moving_offset = 0
	self.ak47.crosshair.steelsight.kick_offset = 0.1
	self.ak47.autohit = autohit_rifle_default
	self.ak47.animations = {}
	self.ak47.animations.fire = "recoil"
	self.ak47.animations.reload = "reload"
	self.ak47.animations.reload_not_empty = "reload_not_empty"
	self.ak47.animations.equip_id = "equip_m4"
	self.ak47.animations.recoil_steelsight = false
	self.ak47.fire_weapon_shaker_multiplier = 0.4
	self.ak47.challenges = {}
	self.ak47.challenges.group = "rifle"
	self.ak47.challenges.weapon = "ak47"
	self.ak47.alert_size = 5000
end
function WeaponTweakData:_create_table_structure()
	self.c45_npc = {
		usage = "beretta92",
		sounds = {},
		use_data = {}
	}
	self.beretta92_npc = {
		usage = "beretta92",
		sounds = {},
		use_data = {}
	}
	self.raging_bull_npc = {
		usage = "beretta92",
		sounds = {},
		use_data = {}
	}
	self.m4_npc = {
		usage = "m4",
		sounds = {},
		use_data = {},
		auto = {}
	}
	self.m14_npc = {
		usage = "m4",
		sounds = {},
		use_data = {},
		auto = {}
	}
	self.r870_npc = {
		usage = "r870",
		sounds = {},
		use_data = {}
	}
	self.mossberg_npc = {
		usage = "r870",
		sounds = {},
		use_data = {}
	}
	self.mp5_npc = {
		usage = "mp5",
		sounds = {},
		use_data = {},
		auto = {}
	}
	self.mac11_npc = {
		usage = "mp5",
		sounds = {},
		use_data = {},
		auto = {}
	}
	self.hk21_npc = {
		usage = "m4",
		sounds = {},
		use_data = {},
		auto = {}
	}
	self.shield_pistol_npc = {
		usage = "shield",
		sounds = {},
		use_data = {}
	}
	self.sniper_rifle_npc = {
		usage = "m4",
		sounds = {},
		use_data = {},
		auto = {}
	}
	self.m79_npc = {
		usage = "m4",
		sounds = {},
		use_data = {},
		auto = {}
	}
	self.glock_18_npc = {
		usage = "beretta92",
		sounds = {},
		use_data = {},
		auto = {}
	}
	self.ak47_npc = {
		usage = "m4",
		sounds = {},
		use_data = {},
		auto = {}
	}
	self.sentry_gun = {
		sounds = {},
		auto = {}
	}
end
function WeaponTweakData:_precalculate_values()
	self.m4_npc.AMMO_MAX = self.m4_npc.CLIP_AMMO_MAX * self.m4_npc.NR_CLIPS_MAX
	self.m14_npc.AMMO_MAX = self.m14_npc.CLIP_AMMO_MAX * self.m14_npc.NR_CLIPS_MAX
	self.c45_npc.AMMO_MAX = self.c45_npc.CLIP_AMMO_MAX * self.c45_npc.NR_CLIPS_MAX
	self.beretta92_npc.AMMO_MAX = self.beretta92_npc.CLIP_AMMO_MAX * self.beretta92_npc.NR_CLIPS_MAX
	self.raging_bull_npc.AMMO_MAX = self.raging_bull_npc.CLIP_AMMO_MAX * self.raging_bull_npc.NR_CLIPS_MAX
	self.r870_npc.AMMO_MAX = self.r870_npc.CLIP_AMMO_MAX * self.r870_npc.NR_CLIPS_MAX
	self.mossberg_npc.AMMO_MAX = self.mossberg_npc.CLIP_AMMO_MAX * self.mossberg_npc.NR_CLIPS_MAX
	self.mp5_npc.AMMO_MAX = self.mp5_npc.CLIP_AMMO_MAX * self.mp5_npc.NR_CLIPS_MAX
	self.mac11_npc.AMMO_MAX = self.mac11_npc.CLIP_AMMO_MAX * self.mac11_npc.NR_CLIPS_MAX
	self.hk21_npc.AMMO_MAX = self.hk21_npc.CLIP_AMMO_MAX * self.hk21_npc.NR_CLIPS_MAX
	self.shield_pistol_npc.AMMO_MAX = self.shield_pistol_npc.CLIP_AMMO_MAX * self.shield_pistol_npc.NR_CLIPS_MAX
	self.sniper_rifle_npc.AMMO_MAX = self.sniper_rifle_npc.CLIP_AMMO_MAX * self.sniper_rifle_npc.NR_CLIPS_MAX
	self.m79_npc.AMMO_MAX = self.m79_npc.CLIP_AMMO_MAX * self.m79_npc.NR_CLIPS_MAX
	self.glock_18_npc.AMMO_MAX = self.glock_18_npc.CLIP_AMMO_MAX * self.glock_18_npc.NR_CLIPS_MAX
	self.ak47_npc.AMMO_MAX = self.ak47_npc.CLIP_AMMO_MAX * self.ak47_npc.NR_CLIPS_MAX
end
